### ISSUE TITLE
Sync?

### ISSUE THREAD

**Issue by galacticwarrior9** [netherfoam/MaxBans-4.0#6]
On the old MaxBans version, there was a sync option, which was immensely important and essential to BungeeCord networks.

Does this still work if you use the same MySQL database for each server? If I recall correctly, this led to caching issues on the old plugin (and thus, sync was required)

**Comment by netherfoam** [comment]
This version doesn't cache bans -- so no sync should be required as long as you're using MySQL :)

I decided it was silly to cache bans, it's better to use database indexes properly

**Comment by galacticwarrior9** [comment]
Hi there!

Thanks a lot for the reply.

Just to move onto an potential bug report, it seems that the user value in the database section of the config is ignored (it tries to connect with root).

`Caused by: java.sql.SQLException: Access denied for user 'root'@'209.222.103.202' (using password: YES)`

The config is configured correctly. For obvious reasons, I have changed the values from their actual ones.

[https://pastebin.com/sPmC1Ywz](url) 

I hope you can look into this!

Best regards

**Comment by netherfoam** [comment]
Ahh -- A simple typo on my part. If you change `user` to `username` in your config - your connection should respect it. eg:

```yml
database:
   driver: "com.mysql.jdbc.Driver"
   url: "jdbc:mysql://sql.ourhost.com:3306/our_database"
   username: "our_username"
   password: "our_password"
   show-sql: false
```
